### PR TITLE
add get size helpers

### PR DESCRIPTION
**Pull request by nihgwu**
I'm creating a `Table` based on `Grid`, it supports tree data and auto growable height, I need to get the total rows' height after expanding/adding/removing or I have to calculate every time it changes manually, right now I have to access the private `_rowSizeAndPositionManager` to get the total height

### CODE REVIEW

**Comment by wuweiweiwu** [comment]
@nihgwu correct me if I'm wrong. But can't you just calculate those values using the required props that you passed into grid?

```js
columnCount
columnWidth
rowCount
rowWidth
```

**Comment by nihgwu** [comment]
@wuweiweiwu `rowHeight` is not constant, then I have to call a reducer to calculate the height every time, it costs too much while the `_rowSizeAndPositionManager` has already got the value

**Comment by nihgwu** [comment]
@TrySound Any opinion on this?

**Comment by wuweiweiwu** [comment]
@nihgwu I see. Thanks for clarifying :)

**Comment by TrySound** [comment]
I think it's good. Let's wait until https://github.com/bvaughn/react-virtualized/pull/1009 will be landed in master.

**Comment by nihgwu** [comment]
@TrySound Thanks, I'm accessing the private instance right now

**Comment by nihgwu** [comment]
@wuweiweiwu updated

**Comment by wuweiweiwu** [comment]
Awesome! I'll make sure tests pass tonight and I'll merge this! Thanks @nihgwu

**Comment by wuweiweiwu** [comment]
Tests all pass locally, merging.

**Pull request merged**
