### PR TITLE
peer dependencies - allow react and react-dom ^17.0.0

### PR DESCRIPTION
**Pull request by liesislukas**
Thanks for contributing to react-virtualized!

#1655 

**Before submitting a pull request,** please complete the following checklist:

- [x] The existing test suites (`npm test`) all pass
- [x] For any new features or bug fixes, both positive and negative test cases have been added
- [x] For any new features, documentation has been added
- [x] For any documentation changes, the text has been proofread and is clear to both experienced users and beginners.
- [x] Format your code with [prettier](https://github.com/prettier/prettier) (`yarn run prettier`).
- [x] Run the [Flow](https://flowtype.org/) typechecks (`yarn run typecheck`).

Here is a short checklist of additional things to keep in mind before submitting:

- Please make sure your pull request description makes it very clear what you're trying to accomplish. If it's a bug fix, please also provide a failing test case (if possible). In either case, please add additional unit test coverage for your changes. :)
- Be sure you have notifications setup so that you'll see my code review responses. (I may ask you to make some adjustments before merging.)

### CODE REVIEW

**Comment by SuPuL** [comment]
Hi @liesislukas,
the dependencies are updated, but there was sadly no new version published as the latest published version is 9.22.3 (December 18, 2020). see https://yarnpkg.com/package/react-virtualized

How is in charge here to publish a new tag?

Greetz

**Comment by SevenOutman** [comment]
Ping @bvaughn

**Comment by samsan1212** [comment]
Ping @bvaughn

**Comment by kishanio** [comment]
Ping @bvaughn

**Comment by olga-f** [comment]
Ping @bvaughn

**Comment by andreieftimie** [comment]
Yeah, we need a new version published for npm to stop complaining about not meeting the correct react dep.

**Comment by joachimklug** [comment]
Ping @wuweiweiwu

**Comment by dominikduda** [comment]
Ping @wuweiweiwu

**Comment by mlnj** [comment]
Ping @bvaughn

**Comment by KYUUUW** [comment]
Ping @bvaughn
Ping @wuweiweiwu

**Comment by ggcaponetto** [comment]
is this library not maintained anymore?

**Comment by andreieftimie** [comment]
> is this library not maintained anymore?

It appears it's not :(

**Comment by vova42matters** [comment]
Any updates? @bvaughn @wuweiweiwu

**Comment by ggcaponetto** [comment]
Switched to [virtuoso](https://github.com/petyosi/react-virtuoso).

**Pull request closed without merging**
