### PR TITLE
Fix broken link on Grid documentation

### PR DESCRIPTION
**Pull request by ivanalejandro0**
Links to sections need to be lowercase.

### CODE REVIEW

**Comment by ivanalejandro0** [comment]
It seems that with this 13085421a5fd4c406697929856bce2ec2263dd0e commit on `master` you overwrited the changes on this PR. I also had to force update the changes on my local `master` branch.

**Comment by bvaughn** [comment]
I believe you're confused. The commit you referenced (1308542) does not touch `docs/Grid.md`, only a few playground/example files.

**Comment by ivanalejandro0** [comment]
Sorry I didn't explain myself correctly, what I think that happened is that when you pushed that commit (13085421a5fd4c406697929856bce2ec2263dd0e) it caused the commit introduced on this PR to be overwritten (most likely required a `git push -f`). 
I guess that the your local `master` and this repo's `master` were out of sync. That may happen if you do some merges using the cli and some merges using the web ui.

Look at the commit history on `master` and you won't find the commit introduced on this PR, also the fix on the `Grid` docs is no longer there.

**Comment by bvaughn** [comment]
Oh! Yes that makes more sense.

I probably merged your PR from my phone in between tweaking the playground files and forgot I needed to pull. My apologies. I'll restore your fix. 😄  Good catch!

**Comment by bvaughn** [comment]
Fixed with 11e28d3.

My apologies! And thanks again for the catch. I'm too used to being the only person working in this repo. I'm a little sloppy at times because of that.

**Comment by ivanalejandro0** [comment]
No worries! This library has been of great help to me so I'm glad of leaving my 2 cents here.
Cheers.

**Pull request merged**
