### PR TITLE
Cover AutoSizer component and its example with types

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
I replaced pre-commit with husky to let lint-staged work. Type checking takes a lot of type on precommit and doing linting for whole project let me see too much shows.

**Comment by TrySound** [comment]
Lint staged processes only staged (changed) files. Husky has more hooks. I just didn't find a way to fix pre commit fail.

**Comment by bvaughn** [comment]
> I just didn't find a way to fix pre commit fail.

Sorry. What do you mean by this? It won't block commits with invalid file formatting?

**Comment by TrySound** [comment]
No it just failed. Maybe I used invalid configuration or something. In any case it works fine now. Can we merge?

**Comment by bvaughn** [comment]
If it works, yes.

**Pull request merged**
