### PR TITLE
WIP flow types

### PR DESCRIPTION
**Pull request by TrySound**
Continue this threads
https://github.com/bvaughn/react-virtualized/issues/405
https://github.com/bvaughn/react-virtualized/pull/426

### CODE REVIEW

**Comment by TrySound** [comment]
I found CellMeasurer `index` prop is not documented

**Comment by bvaughn** [comment]
Hey! I appreciate the work you've done here! 😄

I'm not sure that _replacing_ `propTypes` with Flow types is a good user experience though for the (probably large) percentage of react-virtualized users who _don't_ use the Flow type checker.

It's possible this concern could be addressed with the use of a plugin like [`flow-react-proptypes`](https://github.com/brigand/babel-plugin-flow-react-proptypes) but we would need to make sure there is no user-facing change to the bundled NPM-dist before I'd be willing to move forward with an approach like this.

> I found CellMeasurer `index` prop is not documented

This prob isn't (publicly) documented because it's only a [fallback prop used if the component accidentally passes `index` instead of `rowIndex`](https://github.com/bvaughn/react-virtualized/blob/c828cf2ab0cf35ff2cc7462af02c5269e352df1c/source/CellMeasurer/CellMeasurer.js#L89). I prefer to leave it as kind of a hidden feature.

**Comment by TrySound** [comment]
But propTypes is not used everywhere. Looks like current code base is a bit frankenstein with flow and prop types. But flow fails with 1.5k errors. Should it be used then?
https://github.com/bvaughn/react-virtualized/blob/master/source/CellMeasurer/CellMeasurer.js

**Comment by bvaughn** [comment]
propTypes are used on all user-facing React components. Where is that not the case?

Flow errors because I never actually got around to using it in this project.

**Comment by TrySound** [comment]
I mean maybe then remove flow types completely?

**Comment by bvaughn** [comment]
I don't understand why this is the direction the discussion is taking. Why
does the partial presence of Flow annotations bother you?

If you're interested in RV being fully Flow-typed, I'm supportive of that-
provided it does not break type checking for the majority of library users.
(Also provided it's a feature you're willing to do the work on, because I
don't have the bandwidth for it.)

**Comment by TrySound** [comment]
@bvaughn Yeah. I'm all for that. But can we cover RV with atomic PRs like per component? This let you do more detailed review.

**Comment by bvaughn** [comment]
Great. Then I'm happy to have your help.

I think we have 2 options for how to proceed:

1. Get `flow-react-proptypes` setup and working first (to generate `propTypes` so that the NPM bundle isn't impacted for non-Flow users). After this we could incrementally convert components in master to use Flow through several focused PRs.
1. Incrementally migrate components to use Flow by creating several PRs into a branch _other than master_ and then merge to master once `propTypes` compatibility is settled.

Either way, I think it's important that RV can be released from master in case any critical bugs come up (or in case you lose interest or are otherwise unable to complete the migration).

What do you think?

**Comment by TrySound** [comment]
Agree

**Pull request closed without merging**
