### PR TITLE
Add ScrollTo props to fixed grid elements in MultiGrid

### PR DESCRIPTION
**Pull request by MarkBarbieri**
Thanks for contributing to react-virtualized!

Here is a short checklist of additional things to keep in mind before submitting:
* Please make sure your pull request description makes it very clear what you're trying to accomplish. If it's a bug fix, please also provide a failing test case (if possible). In either case, please add additional unit test coverage for your changes. :)
* Run tests locally (`npm test`) to ensure that your change did not break linting or functionality.
* Be sure you have notifications setup so that you'll see my code review responses. (I may ask you to make some adjustments before merging.)

---

Hi,  I'm using MultiGrid wrapped in an ArrowKeyStepper element (in 'cells' mode).  This is working well but currently only the bottom right grid receives scrollToColumn & scrollToRow props from the parent MultiGrid.  Therefore, if navigating with ArrowKeyStepper in the TopLeft/BottomLeft/TopRight grids they do not receive render events and it is not possible to manage focus.

I've run npm test against this and it's all good.  Thanks

### CODE REVIEW

**Comment by bvaughn** [comment]
Can you add a test (that fails without this change and passes with it)?

**Comment by TrySound** [comment]
@bvaughn probably we shouldn't add features which will be removed or deprecated in major release?

**Comment by MarkBarbieri** [comment]
@bvaughn, I've never written tests before but I can try.  As the grids in question don't have the scrollTo props at the moment I assume that creating a failing test should be easy enough.  

@TrySound, based on your comments, should I be taking a different path here before I consider utilising this functionality in our project?  Is there a change pending that I may not be aware of?

**Comment by TrySound** [comment]
@MarkBarbieri We gonna use props as default values and manipulate scroll with component methods.

**Comment by MarkBarbieri** [comment]
OK.  if you'd prefer not to merge this then in the short term I can probably try and manage this issue via cellRangeRenderer or through forceUpdate() if scrollToColumn/scrollToRow indexes fall into the fixed columns/rows and force rendering and focus.

Sounds like this might be a good use case to test scrolling with component methods, so I'd be more than happy to help test it in this project when you have a working model.

Just to make sure we're on the same page, this is for tracking the row/column of the focused cell when MultiGrid is wrapped in an ArrowKeyStepper component.

**Comment by okonet** [comment]
I'm not sure why it was closed. Is this something that will be fixed in the upstream?

**Pull request closed without merging**
