### PR TITLE
WIP Detect browser for real max element size

### PR DESCRIPTION
**Pull request by TrySound**
Ref #932 
Added naive detectors for chrome, safari, opera and firefox. Can't test edge since I'm on mac, so use default on it. Also didn't test mobile devices. Sadly didn't find info about this with googling.

### CODE REVIEW

**Comment by TrySound** [comment]
Boilerplate for checking
```html
<div style="width: 1.0e+10px; height: 1.0e+10px;"></div>
<script>
const element = document.querySelector('div');
console.log(element.offsetWidth, element.offsetHeight, element.offsetWidth === element.offsetHeight);
</script>
```

**Comment by bvaughn** [comment]
Hey, this is cool. 😄 Does it work? Is it solid enough to release?

**Comment by TrySound** [comment]
Not sure. Browser testers I just googled. Maybe we can use some vendors for this.

**Comment by bvaughn** [comment]
Just curious if you'd smoke tested this and felt like it worked well enough to release.

I like it. I've been meaning to do something like it for a while. I'd love to release it if it's stable enough (eg won't break SSR, has a fallback for IE+Edge, etc)

**Comment by TrySound** [comment]
Didn't try to write SSR test (without jsdom). ie/edge will have default which is already used.

**Comment by bvaughn** [comment]
Ah, shit. I should have tested it a little more before merging.

Set the "Num rows" to "10000000" for the `List` demo page and scroll to the bottom:
screen shot 2018-01-13 at 2 10 23 pm

**Comment by bvaughn** [comment]
Testing more locally, it looks like the max safe value for Chrome (before borders start to blur) is actually closer to 1.67771e+07. This value _renders_ well in Safari too, although drag-scrolling this many pixels in either Safari or Firefox is really bad for perf. Firefox doesn't render reliably anywhere near this high it seems. Borders are arbitrarily darker or thinner at random. 😦 I think I'm going to have to revert this change for now. Or maybe back it out to be only for Chrome.

**Comment by TrySound** [comment]
Hm.. at first it looked good :) I added WIP to not merge this PR yet :)

**Comment by bvaughn** [comment]
Haha, no worries at all. This was my own rushed fault 😄

**Comment by mpospelov** [comment]
Hi guys, I'm not sure if I'm writing in proper place, but seems this PR brokes SSR on latest version
```
ReferenceError: window is not defined
    at isChrome (/Users/mikhailpo/rails_projects/salony-webapp-react/buildServer/webpack:/node_modules/react-virtualized/dist/commonjs/Grid/utils/maxElementSize.js:10:1)
    at getMaxElementSize (/Users/mikhailpo/rails_projects/salony-webapp-react/buildServer/webpack:/node_modules/react-virtualized/dist/commonjs/Grid/utils/maxElementSize.js:14:1)
    at new ScalingCellSizeAndPositionManager (/Users/mikhailpo/rails_projects/salony-webapp-react/buildServer/webpack:/node_modules/react-virtualized/dist/commonjs/Grid/utils/ScalingCellSizeAndPositionManager.js:47:1)
```

**Comment by bvaughn** [comment]
Yikes. Yeah, that looks like. All `window` references should be guarded behind a `typeof window !== "undefined"` check. @TrySound  or @mpospelov would you be willing to submit a PR to fix this? I'm very busy today.

**Comment by TrySound** [comment]
Yep https://github.com/bvaughn/react-virtualized/pull/970

**Comment by TrySound** [comment]
@mpospelov Fixed in 9.17.3

**Comment by bvaughn** [comment]
Woo hoo! Thanks buddy.

**Comment by mpospelov** [comment]
@TrySound Thanks a lot 👍

**Pull request merged**
