### PR TITLE
Adding direction to overscanIndicesGetter

### LINKED ISSUE #627: overscanIndicesGetter doesnt know if its a horizontal or vertical scroll
If you implement `overscanIndicesGetter`, it gets called twice on every scroll event. Once to get the horizontal value and again to get the vertical value.  However, nothing is passed in to let us know which  of these it is.  If we want to return different values for horizontal vs vertical scrolling, it isn't possible.

This is what the code is
```
      const overscanColumnIndices = overscanIndicesGetter({
        cellCount: columnCount,
        overscanCellsCount: overscanColumnCount,
        scrollDirection: scrollDirectionHorizontal,
        startIndex: this._renderedColumnStartIndex,
        stopIndex: this._renderedColumnStopIndex
      })

      const overscanRowIndices = overscanIndicesGetter({
        cellCount: rowCount,
        overscanCellsCount: overscanRowCount,
        scrollDirection: scrollDirectionVertical,
        startIndex: this._renderedRowStartIndex,
        stopIndex: this._renderedRowStopIndex
      })
```

I propose passing another value for horiz/vertical scrolling.  Something like this:

```
      const overscanColumnIndices = overscanIndicesGetter({
        cellCount: columnCount,
        overscanCellsCount: overscanColumnCount,
        scrollDirection: scrollDirectionHorizontal,
        horizontal: true,
        startIndex: this._renderedColumnStartIndex,
        stopIndex: this._renderedColumnStopIndex
      })

      const overscanRowIndices = overscanIndicesGetter({
        cellCount: rowCount,
        overscanCellsCount: overscanRowCount,
        scrollDirection: scrollDirectionVertical,
        horizontal: false,
        startIndex: this._renderedRowStartIndex,
        stopIndex: this._renderedRowStopIndex
      })
```

What do you think?

### PR DESCRIPTION
**Pull request by offsky**
Fixes #627 by adding direction to the overscanIndicesGetter

### CODE REVIEW

**Comment by bvaughn** [comment]
Mind updating the docs as well to list the new parameter? 😄

**Comment by offsky** [comment]
Like that?

**Comment by bvaughn** [comment]
Thanks, but not quite. Update the section below that the hyperlink refers to (`#overscanindicesgetter`)

**Comment by offsky** [comment]
Im sorry, I dont understand. Im happy to make a change if you can elaborate.

**Comment by bvaughn** [comment]
I was just clarifying that- by enabling horizontal scrolling- you're using `List` in a way it's not intended to be used. It's great that everything works (excepting this). I just wanted that clarification.

The reference I made about width being 100% is [here](https://github.com/bvaughn/react-virtualized/blob/120cd3b6d0e3c89722831bba0cb7d4eebe0d30da/source/List/List.js#L172).

**Comment by offsky** [comment]
Brian, I think we got our conversations mixed. This pull request is for my upgrade to the overscanIndicesGetter. Your last comment seems like it was meant for issue #630.   Im happy to update this pull request with better documentation of you can elaborate on what changes you want me to make.

**Comment by bvaughn** [comment]
lol yes sorry. I was responding via email client and I assumed your response was to my most recent comment on the issue. Sorry!

Go look at the [`Grid` props docs](https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md#prop-types). Specifically, the `overscanIndicesGetter` property doesn't defines its interface inline b'c it's hard to read. Instead it links to a [separate section](https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md#overscanindicesgetter). I was requesting you put the interface/params list there. This is similar to how other props (eg [`cellRenderer`](https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md#cellrenderer)) are done. 😄

**Comment by bvaughn** [comment]
👍  Thanks

**Comment by bvaughn** [comment]
9.4.0 was just released with this feature. Thank you for your contribution! I listed you in the [9.4.0 release notes](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#940).

**Pull request merged**
