### PR TITLE
Manual prop types

### PR DESCRIPTION
**Pull request by TrySound**
List of components
- [ ] ArrowKeyStepper
- [x] AutoSizer
- [ ] CellMeasurer
- [ ] Collection
- [x] ColumnSizer
- [ ] Grid
- [x] InfiniteLoader
- [x] List
- [ ] Masonry
- [x] MultiGrid
- [x] ScrollSync
- [x] Table
- [x] WindowScroller

### CODE REVIEW

**Comment by bvaughn** [comment]
Could you explain the motivation for this? It seems undesirable to have to maintain duplicate prop definitions for each component.

**Comment by TrySound** [comment]
https://github.com/bvaughn/react-virtualized/issues/926

**Comment by bvaughn** [comment]
Can we talk about this change first?

**Comment by TrySound** [comment]
commonjs may not work good with esm in the same file. Also I don't like reexporting of prop types. Output code is a bit scary.

**Comment by bvaughn** [comment]
The idea was to use the Flow types to auto-generate the `propTypes`. Flow types are useful for us, while building RV. `propTypes` are useful during runtime, for people using RV.

This PR seems to add redundant Flow and `propTypes` which doubles the maintenance effort. I don't understand why that is required. I'd like to avoid it if possible. Can you explain why it was necessary?

**Comment by billyjanitsch** [comment]
@bvaughn were you able to look at #926? It has a good overview of why this type of change is necessary.

In short, the Babel plugin used to convert Flow types into React PropTypes outputs CJS and does not currently support outputting ESM. This causes [many `require` calls](https://unpkg.com/react-virtualized@9.14.1/dist/es/List/List) to end up in the ESM build of react-virtualized, preventing tree-shaking thereby defeating its purpose. (FWIW it looks like [work has just started](babel-plugin-flow-react-proptypes/pull/162) on supporting ESM output.)

(Another disadvantage of using the plugin is that Flow types can't always map exactly onto PropTypes (e.g. functions), whereas explicit PropTypes make it clear what will be validated for the user at runtime.)

As I mentioned in https://github.com/bvaughn/react-virtualized/issues/926#issuecomment-354404488, the solution that I've seen other libraries use is to add _both_ Flow types and PropTypes, and use a (generic) test to ensure that they stay in sync. It's unfortunate that this solution involves duplication, but I don't see an existing alternative if you want to support a useful ESM build.

**Comment by bvaughn** [comment]
Whoops. Nope, I actually missed the "#926" comment entirely. Thank you for pointing out what I overlooked.

> Another disadvantage of using the plugin is that Flow types can't always map exactly onto PropTypes (e.g. functions), whereas explicit PropTypes make it clear what will be validated for the user at runtime.

I don't follow. Flow types are much more powerful than `PropTypes`. If there was loss of info for, eg a function type, then I wouldn't expect it to be any worse than if you'd defined it as a `PropTypes.func` in the first place. Can you maybe point out an example of what you're talking about?

> the solution that I've seen other libraries use is to add both Flow types and PropTypes, and use a generic test to ensure that they stay in sync. It's unfortunate that this solution involves duplication, but I don't see an existing alternative if you want to support a useful ESM build.

Agreed. This seems like a reasonable solution for the time being. I'd like to see us remove this once brigand/babel-plugin-flow-react-proptypes/pull/162 is merged though! 😄

**Comment by billyjanitsch** [comment]
> If there was loss of info for, eg a function type, then I wouldn't expect it to be any worse than if you'd defined it as a PropTypes.func in the first place.

You're right, I can't imagine a case where you could do _better_ with PropTypes. I'm just pointing out that the loss of info is implicit, i.e. you might use a particular Flow type without realizing that this validation will be lost for the user. Anyway, this is an incidental point.

> This seems like a reasonable solution for the time being. I'd like to see us remove this once brigand/babel-plugin-flow-react-proptypes#162 is merged though!

Yeah, absolutely. Happy to help with either effort this week if that would be useful.

**Comment by bvaughn** [comment]
That would be excellent 😁

**Pull request closed without merging**
