### PR TITLE
Add handleScroll for handling external scroll events

### PR DESCRIPTION
**Pull request by 5angel**
Adds functionality to support easier intergration with custom scrollbars.

See discussion thread:
https://github.com/bvaughn/react-virtualized/issues/692

### CODE REVIEW

**Comment by bvaughn** [comment]
Thanks for submitting this PR.

I added a test for the new method and renamed it to `handleScrollEvent` to hopefully reduce confusion/ambiguity between it and the `scrollToPos` method.

**Comment by bvaughn** [comment]
I just published this feature to NPM as `react-virtualized@9.8.0-rc.1`, tagged `next`. If you'd like to test it pre-release you can via:

```
npm install react-virtualized@next
```

Assuming no problems are reported with the RC, this feature will go out with 9.8.0 sometime this weekend. :grin:

**Comment by bvaughn** [comment]
Haven't heard anything negative about the RC so I just released 9.8.0

**Comment by 5angel** [comment]
nice 👍

**Pull request merged**
