### PR TITLE
Fix undefined height during 1st render of WindowScroller when using scrollElement={domElement} (#1158)

### PR DESCRIPTION
**Pull request by mareolan**
Fix for #1158. Added test case.

### CODE REVIEW

**Comment by Sayvai** [comment]
Is there a reason why this PR bug is not merged in yet? I'm one of several that requires this fix, and the PR was opened back in March...

**Comment by Sayvai** [comment]
@wuweiweiwu ☝️

**Comment by ezetreezy** [comment]
Is this every going to be merged?

**Comment by hata6502** [comment]
I hope this Pull Request merged, too!

**Comment by marine1079** [comment]
Why this PR is not merged yet?

**Comment by marine1079** [comment]
I am waiting it to be merged.

**Comment by PerfectionVR** [comment]
Running into this issue, as well. Please review and merge.

**Comment by andrejpavlovic** [comment]
A workaround I've used:
```typescript
// @ts-expect-error
import { getDimensions } from 'react-virtualized/dist/es/WindowScroller/utils/dimensions';

<WindowScroller scrollElement={container}>
  {({ height, scrollTop, isScrolling, registerChild, onChildScroll }) => {
    if (height === undefined) {
      height = getDimensions(container).height;
    }
   return <>...</>
</WindowScroller>
```

**Pull request closed without merging**
