### PR TITLE
fix: React deprecated findDOMNode method in Table

### PR DESCRIPTION
**Pull request by reliveyy**
Thanks for contributing to react-virtualized!

**Before submitting a pull request,** please complete the following checklist:

- [x] The existing test suites (`npm test`) all pass
- [x] For any new features or bug fixes, both positive and negative test cases have been added
- [x] For any new features, documentation has been added
- [x] For any documentation changes, the text has been proofread and is clear to both experienced users and beginners.
- [x] Format your code with [prettier](https://github.com/prettier/prettier) (`yarn run prettier`).
- [x] Run the [Flow](https://flowtype.org/) typechecks (`yarn run typecheck`).

Here is a short checklist of additional things to keep in mind before submitting:

- Please make sure your pull request description makes it very clear what you're trying to accomplish. If it's a bug fix, please also provide a failing test case (if possible). In either case, please add additional unit test coverage for your changes. :)
- Be sure you have notifications setup so that you'll see my code review responses. (I may ask you to make some adjustments before merging.)

This is a simple workaround for https://github.com/bvaughn/react-virtualized/issues/1353.

### CODE REVIEW

**Comment by olliechick** [comment]
@bvaughn is it possible to merge this PR? It is a small fix that removes strict-mode error

**Comment by cuong-tech** [comment]
@bvaughn any chance we could merge this before EoY please?

**Comment by Npervic** [comment]
Any chance of anyone reviewing this?

**Review by saidmashhud — APPROVED** [review]

**Comment by Noahkoole** [comment]
Please merge this @bvaughn

**Pull request closed without merging**
