### PR TITLE
Add typecheking to test script

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/bvaughn/react-virtualized/pull/730
* added prop types to flow converter
* ignored each components
* ignored node_modules
* replaced npm with yarn in package.json

### CODE REVIEW

**Comment by TrySound** [comment]
CI is not enabled here?

**Comment by bvaughn** [comment]
> CI is not enabled here?

Yes, CI is enabled, although I don't see it being kicked off for this PR. Not sure why.

**Comment by TrySound** [comment]
For previous too.

**Comment by TrySound** [comment]
@bvaughn Are you agree with this PR?

**Comment by bvaughn** [comment]
Haven't had time to do more than glance at it yet, but it looks solid. 👍

**Pull request merged**
