### PR TITLE
chore: Add support for react ^17.0.0 and ^18.0.0

### PR DESCRIPTION
**Pull request by rebelliard**
Adds React ^17 and React ^18 as allowed peer dependencies, so that apps using this library can upgrade React without having to [override](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) any dependencies.

This pull request should superseed https://github.com/bvaughn/react-virtualized/pull/1656.

- [x] The existing test suites (`npm test`) all pass
- [x] For any new features or bug fixes, both positive and negative test cases have been added
- [x] For any new features, documentation has been added
- [x] For any documentation changes, the text has been proofread and is clear to both experienced users and beginners.
- [x] Format your code with [prettier](https://github.com/prettier/prettier) (`yarn run prettier`).
- [x] Run the [Flow](https://flowtype.org/) typechecks (`yarn run typecheck`).

### CODE REVIEW

**Review by bvaughn — APPROVED** [review]

**Comment by rebelliard** [comment]
Is it possible to publish a new version of this library? :D 

PS: Thanks for the hard work here!

**Comment by bvaughn** [comment]
I'm not feeling up for that task right now. Since the last time I published a release, things have changed in master that I haven't tested and can't vouch for.

**Comment by rebelliard** [comment]
Sure! I should be able to look into it during the week. 🙂

**Comment by rebelliard** [comment]
Let me know how I can help. Have a nice day. 🙂

**Comment by bvaughn** [comment]
Sounds good, Rafael. What's your NPM username btw?

**Comment by rebelliard** [comment]
Hey @bvaughn. I tried publishing the NPM package to no avail. I could have sworn I accepted the NPM invitation, but maybe but perhaps I didn't. Could you send it again? :) 

```sh
❯ yarn publish

yarn publish v1.22.18
[1/4] Bumping version...
info Current version: 9.22.3
question New version: 9.23.0
info New version: 9.23.0
[2/4] Logging in...
[3/4] Publishing...

(…)

error Couldn't publish package: "https://registry.yarnpkg.com/react-virtualized: You do not have permission to publish \"react-virtualized\". Are you logged in as the correct user?"

❯ npm whoami

rebelliard
```

**Comment by dgilbertdigital** [comment]
Anyway to get this resolved @rebelliard , @bvaughn? I think this release would help out a lot of people

**Comment by Akhil-Chandran-Arch** [comment]
> Anyway to get this resolved @rebelliard , @bvaughn? I think this release would help out a lot of people

yeah, waiting for the release

**Comment by ezhilkarthi** [comment]
Any update on the release @rebelliard @bvaughn with React 17 or 18 support.

**Comment by cileria** [comment]
Hallo, can you please prioritize this? React-window does not really do it for me. react-virtualized is a great library, react-window does not really do it for me.

**Comment by gabycperezdias** [comment]
@bvaughn Any ETA for the publishing? It appears as if the code is 100% stable for it to be published but it was just a permission issue? Could we retry doing that?

**Comment by cileria** [comment]
> The changes have been published in a fork as https://www.npmjs.com/package/@enykeev/react-virtualized/v/9.22.4-mirror.1. Obviously use at your own discretion.
> 
> Also, be aware, this package has a ton of deprecated and vulnerable dependencies now. It needs active support if want to continue to rely on it.

Thank you so much! How can I install type declarations of this package? I tried:

npm i @types/@enykeev/react-virtualized
npm i @enykeev/@types/react-virtualized

Neither works. Any Idea?

**Comment by enykeev** [comment]
I have not published any type declarations. Given that the types have not changed, you should be able to use original declarations. You may need to somehow hint it to the ts/vscode.

**Comment by taw1313** [comment]
How's this going?

**Comment by fwhatley** [comment]
Any update on the publish for this change? or does anyone have suggestions of other libraries similar to this?

**Comment by LitoMore** [comment]
I opened an issue about this topic:

- https://github.com/bvaughn/react-virtualized/issues/1775

**Comment by tasawar-hussain** [comment]
> I'm not feeling up for that task right now. Since the last time I published a release, things have changed in master that I haven't tested and can't vouch for.
> 
> If you're feeling up for doing this, let's chat?

@bvaughn @rebelliard  Instead of publishing the latest master branch, A new branch can be created from [latest tag](https://github.com/bvaughn/react-virtualized/releases/tag/v9.22.3) as base branch, make these changes in that branch and then create a new tag on that branch and publish the release, in this way only these changes would be part of the release.

I'd be happy to help!

**Comment by ar53n** [comment]
is there any updates?

**Comment by rebelliard** [comment]
Unfortunately, I was not given publishing rights.

```
npm ERR! 403 Forbidden - PUT https://registry.npmjs.org/react-virtualized - You do not have permission to publish "react-virtualized". Are you logged in as the correct user?
```

**Comment by bvaughn** [comment]
Version 9.22.4 has been published with peer dependencies updated to include React 17 and 18. (No other changes from 9.22.3)

https://github.com/bvaughn/react-virtualized/releases/tag/v9.22.4

**Pull request merged**
