### PR TITLE
Collection: cache cell position/size information while scrolling

### PR DESCRIPTION
**Pull request by coluccini**
To avoid unnecessary rendering I've implement a cache for cell's position information in almost the same way the Grid component does

### CODE REVIEW

**Comment by bvaughn** [comment]
Huzzah! Thanks! I'll find time to review this change sometime this morning and- hopefully- push out a bugfix release. :)

**Comment by bvaughn** [comment]
It doesn't seem the rendered cell cache is ever being cleared after scrolling stops (which will cause memory leaks). I will need to think about this a bit.

**Comment by bvaughn** [comment]
Version 7.20.0 has cell caching in `Collection`. Thanks ;)

**Comment by coluccini** [comment]
Awesome! Thanks a lot to you not only because the amazing work you've done with the component but, specially, because how you actively responde to any doubt/request from the developers using it. Your the best!

**Comment by bvaughn** [comment]
Aw, thanks :)

**Pull request merged**
