### PR TITLE
make maxscrollmax size configurable

### PR DESCRIPTION
**Pull request by scarlettlite**
Thanks for contributing to react-virtualized!

Here is a short checklist of additional things to keep in mind before submitting:
* Please make sure your pull request description makes it very clear what you're trying to accomplish. If it's a bug fix, please also provide a failing test case (if possible). In either case, please add additional unit test coverage for your changes. :)
* Run tests locally (`npm test`) to ensure that your change did not break linting or functionality.
* Be sure you have notifications setup so that you'll see my code review responses. (I may ask you to make some adjustments before merging.)

### CODE REVIEW

**Comment by TrySound** [comment]
It's not something which should be configurable. It's constant value which depends on browser abilities.

**Comment by scarlettlite** [comment]
if that is the case how would react virtualised work for react components which have scroll height more than 1.5 million? This breaks 'scrollToRow' use case . I need this to work for my app. Are are any other suggestions ? @TrySound @bvaughn

**Comment by paulkenney** [comment]
@TrySound @bvaughn Is there a specific reason these values should not be changed? Are there specific problems in any specific browsers with higher values?

**Comment by TrySound** [comment]
@paulkenney Yeah, you should find safe values or you will have even bigger problems. For example when chrome reaches limit it just stop render after it. When firefox reaches limit it starts proportionally decrease width. So different browsers even behaves differently. Currently we hardcoded size for chrome which is `1.67771e7 `, others get IE size.

@scarlettlite `scrollToRow` should work. Virtualized scales scroll when the size is more then calculated in this function. Probably you found a bug. Can you create [codesandbox](http://codesandbox.io/) example which reproduces the problem?

**Comment by scarlettlite** [comment]
https://codesandbox.io/s/rl5jv04k3q I created this example the reproduces the issue. Here I take as input the div and where In div ( the vertical offset in div ) I want to scroll to and then compute the scroll top that I pass to the grid . On Safari/Firefox if the scroll Height of the virtualised grid exceeds 1.5 million this calculation fails.

**Comment by mraiguo** [comment]
May I ask, which version of Internet explorer does version 8.x support?

**Pull request closed without merging**
