### PR TITLE
fix for #998

### PR DESCRIPTION
**Pull request by dcolens**
This is a fix + tests for issue #998. Note that this is a partial fix as it covers only rows, submitting it for review. It it looks good, I can try doing the same for columns :-)

### CODE REVIEW

**Comment by bvaughn** [comment]
Scanned through super quickly (on my way to lunch). At a glance the fix looks reasonable! And I love the fact that there's a test.

The ternary within a boolean conditional looked strange but that's a nit.

If you'd be willing to do the fix for column too, please do!

**Comment by dcolens** [comment]
i'm not a fan of the ternary + boolean too, an alternative is something like:
```javascript
  this._recomputeScrollLeftFlag = scrollToColumn >= 0 
    ? (this.state.scrollDirectionHorizontal === SCROLL_DIRECTION_FORWARD 
      ? columnIndex <= scrollToColumn
      : columnIndex >= scrollToColumn)
    : false;
```
Let me know if you prefer the above snippet and I'll update the pull request!

**Comment by dcolens** [comment]
Any chance this gets merged soonish ?

**Comment by dcolens** [comment]
@bvaughn sorry to bug you, but I'd really like to get this one fixed, when do you think it can be merged ?

**Comment by jwickens** [comment]
WOW, this is so much better for my chat use case, thanks @dcolens. BTW when I published this to our private NPM to try it out I had to run `yarn lint --fix` because of some eslint issues.

**Comment by dcolens** [comment]
weekend is coming ! 

time for a merge ?

**Comment by diogofcunha** [comment]
Thanks for your contribution @dcolens, gonna carry out some testing on this an hopefully we can merge it very soon.

**Comment by wuweiweiwu** [comment]
@dcolens This is currently blocked by #1053 which is a major rewrite of `Grid.js` We will try to merge ASAP as soon as thats done. :)

**Comment by wuweiweiwu** [comment]
@dcolens Do you mind putting the fix + tests and columns in this PR? That'll be amazing

**Comment by wuweiweiwu** [comment]
Wait nevermind. Merging

**Comment by bvaughn** [comment]
Looks like this broke CI?

https://circleci.com/gh/bvaughn/react-virtualized/2102

**Pull request merged**
