### PR TITLE
Allow Grid column/row sizes to be specified as a percentage and use a…

### PR DESCRIPTION
**Pull request by trevorr**
… 100% column for VirtualScroll

### CODE REVIEW

**Comment by bvaughn** [comment]
Hey @trevorr,

Thanks for the contribution. I appreciate the time you've spent. I'm going to need to give this some careful thought and consideration (which I probably won't have the time to do until the weekend). I'm initially very wary of introducing another forking path here WRT cell measurements because it increases my maintenance effort in the future. But I'll give it some thought. :)

**Comment by trevorr** [comment]
I understand. An alternative approach I considered was adding a "single column mode" to `Grid` that `VirtualScroll` enables. It would set the container and cell widths to 100%. It would have been less code and in some ways easier to understand, but I chose the other approach because "single column mode" felt like a special case hack that might not play well with other features. It also begged the question of why not "single row mode" too, which probably then would have netted the same amount of code, but with lots of `if` statements instead of polymorphism.

**Comment by bvaughn** [comment]
Okay. Back to thinking about this a little.

I feel like percentage widths for columns would be better as a HOC - something similar to [`ColumnSizer`](https://github.com/bvaughn/react-virtualized/blob/master/source/ColumnSizer/ColumnSizer.js). I'm really reluctant to fork the cell measuring logic and add more complexity to `Grid`.

What do you think about a HOC approach? We could even use the `dom-helpers/util/scrollbarSize` util to measure the scrollbar size and take that into account when it comes to calculating the column widths.

**Comment by bvaughn** [comment]
Actually I wonder if we could even roll this functionality _into_ `ColumnSizer` ?

**Comment by bvaughn** [comment]
Actually- thinking more about the specific problem you're trying to solve here- I wonder if we couldn't help things along a bit more by passing scrollbar width as a new name parameter to `cellRenderer`.

**Comment by bvaughn** [comment]
Although if all you want is support for 100% column width in `VirtualScroll` ... you might not even need the `ColumnSizer` work. You could just rely on the new `horizontalScrollBarSize` property passed to `cellRenderer` and size your cell accordingly?

**Comment by bvaughn** [comment]
Just ignore the above ramblings. ;) I'm going to take a quick shot at this myself this morning. I have a few minutes before work. Will check back in shortly.

**Comment by bvaughn** [comment]
It's been a few days since I've been able to think about this. I had another idea.

A couple of small adjustments to `Grid`...
```diff
diff --git a/source/Grid/Grid.js b/source/Grid/Grid.js
index 655d51f..c631311 100644
--- a/source/Grid/Grid.js
+++ b/source/Grid/Grid.js
@@ -449,6 +449,7 @@ export default class Grid extends Component {
 
   render () {
     const {
+      autoHeight,
       cellClassName,
       cellRenderer,
       cellRangeRenderer,
@@ -459,7 +460,6 @@ export default class Grid extends Component {
       noContentRenderer,
       overscanColumnCount,
       overscanRowCount,
-      autoHeight,
       rowCount,
       style,
       tabIndex,
@@ -580,7 +580,7 @@ export default class Grid extends Component {
           <div
             className='Grid__innerScrollContainer'
             style={{
-              width: totalColumnsWidth,
+              width: columnCount === 1 ? 'auto' : totalColumnsWidth,
               height: totalRowsHeight,
               maxWidth: totalColumnsWidth,
               maxHeight: totalRowsHeight,
diff --git a/source/Grid/defaultCellRangeRenderer.js b/source/Grid/defaultCellRangeRenderer.js
index 713ceb1..c7d9918 100644
--- a/source/Grid/defaultCellRangeRenderer.js
+++ b/source/Grid/defaultCellRangeRenderer.js
@@ -68,11 +68,11 @@ export default function defaultCellRangeRenderer ({
           key={key}
           className={cn('Grid__cell', className)}
           style={{
-            ...cellStyleObject,
             height: rowDatum.size,
             left: columnDatum.offset + horizontalOffsetAdjustment,
             top: rowDatum.offset + verticalOffsetAdjustment,
-            width: columnDatum.size
+            width: columnDatum.size,
+            ...cellStyleObject
           }}
         >
           {renderedCell}
```
...would allow this to be accomplished by specifying a `rowClassName` or `rowStyle`:

### Style
```js
<VirtualScroll
  rowStyle={{ width: '100%' }}
  {...otherProps}
/>
```

### Class name

```js
<VirtualScroll
  rowClassName={styles.rowWrapper}
  {...otherProps}
/>
```
```css
.rowWrapper {
  width: 100% !important;
}
```

This approach feels a _little_ hacky as well but it avoids the 150+ line layout and measurement fork.

Thoughts? Reactions?

**Comment by trevorr** [comment]
I think that seems fine. Just a few questions:

- Does this still allow a `Grid` that is not part of a `VirtualScroll` to have a single column wider than the `Grid` and scroll it?
- I've been wondering, is setting `maxWidth` and `maxHeight` to be the same as `width` and `height` (respectively) on the container not redundant? Similarly, what is the effect of setting `width: auto` and `maxWidth` equal to the `Grid` width? Could that result in hiding part of the row again in some cases, or does row `width: 100%` prevent that and make the container `maxWidth` irrelevant?
- Would you have `VirtualScroll` work this way by default, or would any user wanting this behavior have to override the row width as shown? I would think the proposed behavior would always be desired, but maybe there's a compatibility concern?

**Comment by bvaughn** [comment]
> Does this still allow a Grid that is not part of a VirtualScroll to have a single column wider than the Grid and scroll it?

Assuming the cell/column width is greater than the `Grid` width then yeah, it should still be scrollable.

> I've been wondering, is setting maxWidth and maxHeight to be the same as width and height (respectively) on the container not redundant? Similarly, what is the effect of setting width: auto and maxWidth equal to the Grid width? Could that result in hiding part of the row again in some cases, or does row width: 100% prevent that and make the container maxWidth irrelevant?

I don't recall if I specifically need the max width/height or if I'm just setting them out of caution. Setting the width/height is important though and 100% wouldn't work. The size of the inner container is what makes the `Grid` scrollable, and then based on scroll position- RV decides which columns to render. If we used 100% or _just_ max width/height, the `Grid` wouldn't be scrollable b'c it would only contain the initially rendered cells. (Or if it was scrollable it would only be scrollable in so much as the overscan rows/columns made it scrollable.)

> Would you have VirtualScroll work this way by default, or would any user wanting this behavior have to override the row width as shown? I would think the proposed behavior would always be desired, but maybe there's a compatibility concern?

I think I'd probably make `VirtualScroll` and `FlexTable` default to this behavior.

**Comment by trevorr** [comment]
Sounds good to me then. I'll close this PR and we can go with your change for fixing #279.

**Pull request closed without merging**
