### PR TITLE
Episode 9.0 (The One About React Fiber)

### PR DESCRIPTION
**Pull request by bvaughn**
To test version 9 yourself- `npm i react-virtualized@next`

You can also give it a spin [on the demo site](https://bvaughn.github.io/react-virtualized/) which is now powered by React fiber too!

# Remaining TODO items

- [x] ~~`CellMeasurerCache` should cache and return an average cell size as a sub for an unknown cell's `width`/`height` (instead of `minWidth`/`minHeight`). This will make it more accurate over time when estimating layout of previously unmeasured cells.~~ (deferred)
- [x] Add a few remaining unit tests for new functionality
- [x] Update docs and write a better upgrade guide

# Non-breaking changes

The following backwards-compatible issues will be addressed with version 9:

#### Bug fixes:
  * #532: iOS scroll bounce fix
  * #559: Added public method `forceUpdateGrids` to `MultiGrid` that calls `forceUpdate` on all child `Grid`s.
  * #561: Per item caching
  * #568: `Collection.forceUpdate()` now calls `forceUpdate` on inner `CollectionView`
  * #576: Rendering problems for `Grid` with huge number of rows
#### New features:
  * #554: Overscan direction can be customized using the new `overscanIndicesGetter` prop [for `Grid`](https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md#prop-types).
  * #578: Presentational `Table` styles now support iOS 8.4
#### DEV mode warnings:
  * Use of `CellMeasurer` with an improperly configured `Grid` will now log a warning.
  * `Grid` cells rendered without a `style` prop now log a warning.

# Backwards-breaking changes

* **Supported React versions have changed.** Previously all React 14 and 15 releases were supported. Going forward only React 15.3 and newer will be supported. This was done to drop a peer dependency on `react-addons-shallow-compare` and replace it with `React.PureComponent` [as the docs suggest](https://facebook.github.io/react/docs/shallow-compare.html).
screen shot 2017-02-13 at 1 44 43 pm

* **`CellManager` has been completely rewritten to support fiber.** It's more flexible than before but uses a very different syntax. See below for more detailed instructions on how to upgrade.

### `CellMeasurer` changes

Previously, `CellMeasurer` wrapped a `Grid` and measured all rows and/or columns, like so:

```jsx
<CellMeasurer
  cellRenderer={cellRenderer}
  cellSizeCache={cellSizeCache}
  columnCount={columnCount}
  rowCount={rowCount}
>
  {({ getColumnWidth, getRowHeight }) => (
    <Grid
      columnCount={columnCount}
      columnWidth={getColumnWidth}
      cellRenderer={cellRenderer}
      rowCount={rowCount}
      rowHeight={getRowHeight}
      {...otherProps}
    />
  )}
</CellMeasurer>
```

This had one major drawback: `CellMeasurer` could not be used to measure only specific rows/columns. A secondary, related drawback was that cell measurements were cached by index. Because of this insertions, deletions, and re-ordering invalidated measurements and require re-measuring.

The new `CellMeasurer` wraps individual cells, allowing selective measurement. By providing a `keyMapper`, measurements can also be cached by cell ID instead of index- making them reusable after insertions, deletions, and re-orders. The new syntax for using `CellMeasurer` is like so:

```jsx
// In this example, average cell width is assumed to be about 100px.
// This value will be used for the initial `Grid` layout.
// Cell measurements smaller than 75px should also be rounded up.
// Height is not dynamic.
const cache = new CellMeasurerCache({
  defaultWidth: 100,
  minWidth: 75,
  fixedHeight: true
});

function cellRenderer ({ columnIndex, key, parent, rowIndex, style }) {
  const content // Derive this from your data somehow

  return (
    <CellMeasurer
      cache={cache}
      columnIndex={columnIndex}
      key={key}
      parent={parent}
      rowIndex={rowIndex}
    >
      {content}
    </CellMeasurer>
  );
}

function renderGrid (props) {
  return (
    <Grid
      {...props}
      columnWidth={cache.columnWidth}
      deferredMeasurementCache={cache}
      cellRenderer={cellRenderer}
    />
  );
}
```

### CODE REVIEW

**Comment by edulan** [comment]
Can't wait to play with the new CellMeasurer :smile:

Thanks a lot for all the work @bvaughn!!!

**Comment by bvaughn** [comment]
D'oh! Sorry @edulan I missed your comment. Thank you!

I plan a final release soon- but until then you can play with it via `npm i react-virtualized@next` if you'd like to give it a spin early. I don't expect the API to change any. I'm mostly finishing up documentation and adding a few more automated tests.

**Comment by romulof** [comment]
Isn't Fiber only being enabled by default in React 16?
If so, the new CellMeasurer would require React 16 as dependency.

**Comment by bvaughn** [comment]
`CellMeasurer` doesn't require React 16 to work. React 16 won't work with react-virtualized <= 8 though because the subtree/portal render method `CellMeasurer` used to use- which used to be synchronous- is asynchronous in React 16. So I rewrote `CellMeasurer` to support async out of the box and it is now compatible with React 16 (and older).

I did bump the React peer dependency up to 15.3 though because I wanted to use `PureComponent` and stop requiring people to also instead `react-addons-shallow-compare` for the `shallowCompare` util.

**Comment by romulof** [comment]
Great. I thought you were using some Fiber-specific feature.

I still need to invalidate/update cache if a cell changes size or this new CellMeasurer handles it automatically?

**Comment by bvaughn** [comment]
Still need to manually invalidate. Otherwise I'd have to force layout frequently which would defeat the purpose.

**Comment by romulof** [comment]
Using this new CellMeasurer still renders the cell twice (for measure and actual rendering) ?

**Comment by bvaughn** [comment]
Yes. You could prevent the second render (if it's worth it) using `shouldComponentUpdate`. The only prop that should change is the incoming `style` (which will have actual instead of estimated measurements).

**Comment by mquan** [comment]
@bvaughn Is the way to manually trigger cell re-measurement [here](http://stackoverflow.com/a/40659812) still valid?  If not, can you point me to documentation of the new way of doing it for CellMeasurer & Grid combo? thanks

**Comment by bvaughn** [comment]
@mquan The way to clear measurements now is to reset your `CellMeasurerCache`:

```js
// Clear measurements so CellMeasurer will know to re-measure when it is next rendered
cellMeasurerCache.clearAll()

// Let Grid know to clear its cached position data and re-render
gridRef.recomputeGridSize()
```

**Comment by kirtimukha** [comment]
Maybe it's very simple question, but please understand I'm very new on react. 
Can you let me know where do I put the cellMeasureCache.clearAll() function?
I'm having a proble lists are disappear when I scrolled up. 
I used "cache.clear()" on " isRowLoaded (){ here:where i put the cache.clear() }"function now. 


and this is my retunr   <article className="wrap-article">
          {/*
                    <div
                        className="article img _0 clearfix"
                    >
                        <div className="cont no-article clearfix">
                                                      
                        </div>
                    </div>
                    */}
          <>

              <AutoSizer >
                {({ width, height }) => (
                  <InfiniteLoader
                  isRowLoaded={this.isRowLoaded.bind(this)}
                  loadMoreRows={this.fetchFeed.bind(this)}
                  rowCount={5}
                >
                 {({ onRwsRendered, registerChild }) => (
                    <List
                      height={height}
                      autoHeight
                      width={width}
                      overscanRowCount={0}
                      rowCount={this.state.community_list.length}
                      rowHeight={this.cellMeasurerCache.rowHeight}
                      rowRenderer={this.renderRow.bind(this)}
                      onRowsRendered={onRwsRendered}
                      deferredMeasurementCache={this.cellMeasurerCache}
                      onScroll={this.scrollListener}
                      ref={registerChild}
                      className="ReactVirtualize_customClass"
                    />
                  )}
                </InfiniteLoader>
              )}
            </AutoSizer>
            </>
        </article>


Can you help me?

**Pull request merged**
