### PR TITLE
Fix position offset computing for window

### PR DESCRIPTION
**Pull request by TrySound**
The case is visible when you scroll down 3000px, do small resize and scroll again. Viewport is cleaned. documentElement relativity is different.

### CODE REVIEW

**Comment by TrySound** [comment]
@bvaughn Tried to use puppeteer. There's a lot of boilerplate in installing and bootstrapping, but hope it can be resolved soon.

**Comment by TrySound** [comment]
Don't know how to fix it. Without sandboxing the error looks like this
```
Error: Failed to launch chrome!
/home/circleci/project/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/circleci/project/node_modules/puppeteer/lib/Launcher.js:211:14)
    at Interface.helper.addEventListener (/home/circleci/project/node_modules/puppeteer/lib/Launcher.js:200:50)
    at Interface.emit (events.js:164:20)
    at Interface.close (readline.js:381:8)
    at Socket.onend (readline.js:154:10)
    at Socket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by TrySound** [comment]
I asked in local slack. Guys say all is good in travis.

**Comment by TrySound** [comment]
I'm gonna merge this and open PR with enabled e2e tests. Hope once it will be merged :)

**Comment by bvaughn** [comment]
Hey Bogdan. Thanks for running with this. 😄 

I've been spending time offline the past few days because I had family visiting from the East coast for the holidays. Happy to see you moved forward without being blocked.

**Comment by TrySound** [comment]
Happy holidays!

**Pull request merged**
