### PR TITLE
make test in react-test-renderer painless

### PR DESCRIPTION
**Pull request by nihgwu**
ref #1117

### CODE REVIEW

**Comment by nihgwu** [comment]
Done, without this change, the tests will fail

**Comment by nihgwu** [comment]
BTW, can we release a new version? that breaks all my test cases, now I have to use a wrapper to apply the mock option, also I don't think that's the desired solution, as that would make people thought I was using refs in `cDM` of my `Table` but that's not true

**Comment by wuweiweiwu** [comment]
@nihgwu yep We'll release a minor soon. Probably after I fix #1119 . So for now, you'll have to use `createNodeMock` locally

**Comment by wuweiweiwu** [comment]
Thanks for contributing @nihgwu !

**Comment by wuweiweiwu** [comment]
this is released in 9.20.0!

**Comment by wuweiweiwu** [comment]
a work around is to use `createNodeMock`

**Comment by ivosh** [comment]
@wuweiweiwu Excellent! This is really appreciated.

**Pull request merged**
