### PR TITLE
Update peer dependencies to allow React 17

### LINKED ISSUE #1616: Support React 17
Currently, `react-virtualized` has a peer dependency on `react` and `react-dom` that constraints it to React 16. From my experiments, it already seems to work with React 17 so this might be as simple as just bumping the bounds.

### PR DESCRIPTION
**Pull request by levenleven**
Fixes #1616

- [x] The existing test suites (`npm test`) all pass
- [x] Format your code with [prettier](https://github.com/prettier/prettier) (`yarn run prettier`).
- [x] Run the [Flow](https://flowtype.org/) typechecks (`yarn run typecheck`).

### CODE REVIEW

**Comment by levenleven** [comment]
Tested manually of course. And we're using react-virtualized + react 17 in production for quite a while now

**Comment by edowney29** [comment]
Bump to get this pushed through. Thanks!

**Comment by msgitb** [comment]
Bump. This would help a lot, thanks.

**Review by JulesPatry — APPROVED** [review]

**Comment by pm-mkorpar** [comment]
any updates on this, would be super helpfull :)

**Comment by SourceCipher** [comment]
Is this library still being updated? As judging from the PRs dating months and months back, nobody is doing anything. I want to submit a PR as well but seeing the progress seems like a time consuming task

**Comment by hklsiteimprove** [comment]
@bvaughn is there any chance we can get this in?

**Comment by An6r** [comment]
hey! can we get an update?

**Comment by hklsiteimprove** [comment]
hey @yamadapc. @bvaughn seem to not be actively doing stuff only more. Is there a chance you can merge this?

**Comment by jarekucinski** [comment]
Bump. This would help a lot, thanks.

**Review by wuweiweiwu — APPROVED** [review]
Thanks for this update! will update the thread when it is released!

perhaps it is time to rewrite with hooks (maybe v10?) but that will definitely take time

**Comment by pavithrakareti** [comment]
@wuweiweiwu  Thank you for merging it . Is there a timeline on when it would be released ?

**Comment by tmarcinkowski-logitech** [comment]
@wuweiweiwu Could you release a new version with these changes, please? :-)

**Comment by mcreations** [comment]
Still blocked without this. A release with this is greatly appreciated.

**Comment by SamLeatherdale** [comment]
Would be awesome to get a release for this, now in 2022 with React 18 already released 🙏

**Comment by nostalgiaz** [comment]
Please release it <3

**Comment by DavidRochelTR** [comment]
Bump for release

**Pull request merged**
