### PR TITLE
Use row/column indexes % the number of visible cells as React keys

### PR DESCRIPTION
**Pull request by clauderic**
Initial testing with [fps-measurer](https://github.com/bvaughn/fps-measurer) shows improvement of about about 5-10 fps over previous implementation.

### CODE REVIEW

**Comment by bvaughn** [comment]
Whoa! 5-10 fps increase is fantastic!

I'll review this pR this evening. Can't wait to test it out myself! Thanks!

**Comment by bvaughn** [comment]
Interesting. Initial findings are ~5 FPS increase for `Grid` test but ~2 FPS decrease for `FlexTable` test.

| react | react-virtualized | [grid-test](http://github.com/bvaughn/react-virtualized/tree/master/playground/grid-test.js) FPS | [table](http://github.com/bvaughn/react-virtualized/tree/master/playground/table.js) FPS |
| --- | --- | --- | --- |
| 0.14.8 | 7.11.2 | 35.59 | 39.61 |
| 0.14.8 | branch | 39.69 | 37.75 |
| 15.1.0 | 7.11.2 | 37.93 | 38.72 |
| 15.1.0 | branch | 41.6 | 37.44 |
| dev master | 7.11.2 | 36.11 | 39.12 |
| dev master | branch | 41.17 | 35.5 |

**Comment by bvaughn** [comment]
Interesting! Despite the re-painting concerns, changing my `Grid` test harness to scroll up instead of down yields 28.73 fps for `master` and 37.07 for this branch.

**Comment by bvaughn** [comment]
Ran again for `Grid`, this time on an external monitor with a larger browser window. When scrolling up- this branch got ~36 fps vs ~16 fps for `master`. Scrolling down this branch got ~44.8 fps vs ~34.6 fps on `master`. Wow!

**Comment by bvaughn** [comment]
External monitor, larger browser test for `FlexTable` shows 40.45 fps scrolling down for this branch vs 46.76 on `master`. Scrolling up gets 32.12 fps for this branch vs 46.27 fps for `master`.

So findings are consistent that it's slower for `FlexTable` but faster for `Grid`. I wonder if it has to do with the complexity of cells? In the `Grid` test harness, cells are basically just a span with text. In the `FlexTable` test harness each `Grid` cell is a full "table" row (flexbox container).

**Comment by bvaughn** [comment]
If I increase the "complexity" of the `Grid` cell in that test harness, FPS for this branch drops considerable (10.96 fps fps vs 10.19 fps for `master`). If I increase it more, FPS for this branch drops to 8.31 fs 8.22 for `master`. It looks like as the complexity of the cells increases, the difference between the 2 approaches shrinks noticeably.

That makes sense. Most of the time is now being spent scripting so the layout/repainting gains don't matter so much.

Still not sure why `FlexTable` shows an _opposite_ effect though. More testing necessary still.

**Comment by bvaughn** [comment]
Haven't forgotten about this, just unclear on how to proceed with it. Seems like the results are mixed. Not sure if you have had any insights since we last chatted?

**Comment by clauderic** [comment]
I haven't had time to dig back into this yet, but to summarize (should anybody want to collaborate on this):
The number of items rendered needs to be constant to truly reap the benefits of recycling the nodes (otherwise it needlessly causes repaints, which is why we were seeing mixed results). While the idea of always maintaining a fixed number of rows/columns rendered could be feasible for fixed width/height items, it breaks down for elements of varying heights. 

Need to give this some more thought...

**Comment by bvaughn** [comment]
Hey @clauderic.

I'm going to close this PR for now b'c I don't like leaving long-running PRs open. (Gives a conflicting message to newcomers who may want to contribute.)

Last time we talked about this, the findings were pretty mixed and it wasn't clear that this change set was an _improvement_. If you find more time to look into it- or if I do- I'd be happy to pick back up where we left off and re-open this PR though. Always looking for ways to squeeze out more perf. :D

**Pull request closed without merging**
