### PR TITLE
Enable e2e test on ci

### PR DESCRIPTION
**Pull request by TrySound**
Ref #920

### CODE REVIEW

**Comment by bvaughn** [comment]
I assume this is unexpected?
screen shot 2017-12-30 at 9 24 00 am

**Comment by TrySound** [comment]
Yep. Tried a lot of combinations for puppeteer config, nothing helped. My friends said travis works fine with it.

**Comment by TrySound** [comment]
If disable sandbox as troubleshooting section said you will see some native lib is not found.

**Comment by TrySound** [comment]
It's possibly debian problem

**Comment by bvaughn** [comment]
I think I'm missing some context here then. If we merge this, it will break CI. Are you suggesting we add Travis integration for some tests? or instead of CircleCI? or...? What am I missing?

This PR references #920 but I don't see where that explains why CI is expected to fail and what the plan is to fix it?

**Comment by TrySound** [comment]
I added puppeteer for e2e tests, but wasn't successful in running it on circle ci machine.

**Comment by TrySound** [comment]
So disabled it temporary. Wanna fix the problem here.

**Comment by TrySound** [comment]
@bvaughn It works finally!

**Comment by bvaughn** [comment]
Nice!

**Pull request merged**
