### PR TITLE
Prefer react namespace over default export

### PR DESCRIPTION
**Pull request by TrySound**
Thanks for contributing to react-virtualized!

Here is a short checklist of additional things to keep in mind before submitting:
* Please make sure your pull request description makes it very clear what you're trying to accomplish. If it's a bug fix, please also provide a failing test case (if possible). In either case, please add additional unit test coverage for your changes. :)
* Run tests locally (`npm test`) to ensure that your change did not break linting or functionality.
* Be sure you have notifications setup so that you'll see my code review responses. (I may ask you to make some adjustments before merging.)

### CODE REVIEW

**Comment by bvaughn** [comment]
Why?

**Comment by TrySound** [comment]
https://github.com/bvaughn/react-virtualized/pull/1021#issuecomment-369129661

**Comment by bvaughn** [comment]
Would it be sufficient to change this:
```js
import React, {PureComponent} from 'react';

class AutoSizerExample extends PureComponent<{}, State> {
```
To this:
```js
import React from 'react';

class AutoSizerExample extends React.PureComponent<{}, State> {
```
Just curious.

**Comment by TrySound** [comment]
Okay. I just think `import * as React` is more future friendly.

**Comment by bvaughn** [comment]
I'm not really opposed to the "import * as" syntax. I was just curious.

If you think it's the right move in our source code, I don't strongly object.

**Pull request merged**
