### PR TITLE
Update detectElementResize to support rendering into iframes and child windows

### PR DESCRIPTION
**Pull request by ahutchings**
Without these changes, the size of elements rendered in remote windows is incorrectly detected as height 0/width 0.

* Create detectElementResize CSS in the document containing the rendered AutoSizer.
* Create the resize trigger element using the document containing the rendered AutoSizer.

I'm not sure how to go about testing for this change - any suggestions are welcome.

### CODE REVIEW

**Comment by bvaughn** [comment]
Can you point me at an example of the type of thing you're trying to do that this change enables? A Codesandbox demo would be great!

**Comment by ahutchings** [comment]
Sure, I created a Codesandbox here: https://codesandbox.io/s/nro7yzrqv0

Two popup windows are opened -

The one with the red square is using the unpatched version of react-virtualized, so the detectElementResize CSS is not appended to its document <head> tag, and so the square does not resize.

The one with the green square is using the changes in this PR, which append the detectElementResize CSS to the owning document of the AutoSizer's parent node.

**Comment by bvaughn** [comment]
Both pop-up windows appear to resize the same for me.

**Comment by ahutchings** [comment]
Oops, turns out some of those changes are needed for Chrome, but not for Firefox. Working on adding them back now.

**Comment by ahutchings** [comment]
Pushed a new commit and updated the Codesandbox. It now works properly in both Chrome and Firefox.

**Comment by TrySound** [comment]
@bvaughn Is it possible to cover it with puppeteer tests?

**Comment by bvaughn** [comment]
I dunno. Maybe?

**Comment by TrySound** [comment]
@ahutchings Would you like to take care about test for this case?

**Comment by ahutchings** [comment]
Sure, I will take a look at creating a test case for this. Looks like I can use the WindowScroller end-to-end test as an example.

**Comment by bvaughn** [comment]
Nice! Thanks!

**Pull request merged**
